import { describe, expect, it } from 'vitest'
import { readFile } from 'node:fs/promises'

describe('native @ reference client', () => {
  it('binds settings scope methods without losing the controller receiver', async () => {
    const source = await readFile(new URL('../src/client/ReferenceSettingsCard.tsx', import.meta.url), 'utf8')
    expect(source).toContain('listener => props.settingsScope.subscribe(listener)')
    expect(source).toContain('() => props.settingsScope.getSnapshot()')
    expect(source).not.toContain('useSyncExternalStore(props.settingsScope.subscribe, props.settingsScope.getSnapshot)')
  })

  it('registers all data tabs without an iframe or external-window path', async () => {
    const source = await readFile(new URL('../src/client/index.tsx', import.meta.url), 'utf8')
    expect(source).toContain("createOnlineSource('pinterest', 'Pinterest'")
    expect(source).toContain("createOnlineSource('zlibrary', 'Z-Library'")
    expect(source).toContain("menuLayout: provider === 'pinterest' ? 'masonry' : 'book-list'")
    expect(source).toContain("menuLayout: 'project-grid'")
    expect(source).toContain("menuLayout: 'repository-list'")
    expect(source).toContain('createCodePenSource(catalog, t)')
    expect(source).not.toContain("online.search('codepen'")
    expect(source).toContain('thumbnail: result.imageUrl')
    expect(source).toContain("t('action.download')")
    expect(source).toContain("t('action.save')")
    expect(source).toContain("'action.pinterest-login' : 'action.pinterest-open'")
    expect(source).not.toContain('onlinePlaceholder')
    expect(source).not.toContain('request.query.trim().length < 2')
    expect(source).not.toContain('normalized.length < 2')
    expect(source).toContain('normalized.length === 1')
    expect(source).toContain('CODEPEN_POSTER_ENDPOINT')
    expect(source).toContain('CODEPEN_PREVIEW_ENDPOINT')
    expect(source).toContain("ctx.slots.inject('settings.plugin.item'")
    expect(source).toContain('REFERENCE_LIBRARY_SETTINGS_NAMESPACE')
    expect(source).toContain('loadPinterestBridgeStatus')
    expect(source).toContain('pinterestOpenUrl')
    expect(source).toContain('PinterestMenuRefresh')
    expect(source).toContain('subscribeLexicon')
    expect(source).toContain('menuControls')
    expect(source).toContain('onMenuControl')
    expect(source).toContain('loadMore')
    expect(source).toContain('PINTEREST_LOAD_MORE_EVENT')
    expect(source).not.toContain('Pinterest OAuth')
    expect(source).not.toContain('remote.credentials')
    expect(source).not.toContain('<iframe')
    expect(source).not.toContain('window.open')
    expect(source).not.toContain('panel:')
  })
})
