export const styles = `
.dmp-sidebar{display:flex;height:100%;min-height:0;flex-direction:column;gap:8px;padding:0 8px 10px;color:var(--dsw-alias-label-primary)}
.dmp-source-select{display:grid;flex:0 0 auto;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:10px;padding:0 4px;font-weight:600}.dmp-source-select select{box-sizing:border-box;width:100%;min-width:0;height:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;padding:0 28px 0 12px;background:var(--dsw-alias-bg-base);color:inherit;font:inherit;font-size:12px;font-weight:500;cursor:pointer}
.dmp-sidebar-search{display:grid;flex:0 0 auto;grid-template-columns:minmax(0,1fr) 34px;gap:6px}.dmp-input{box-sizing:border-box;width:100%;height:34px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:0 10px;background:var(--dsw-alias-bg-base);color:inherit;font:inherit}.dmp-search-button,.dmp-play-toggle{appearance:none;display:grid;place-items:center;border:0;border-radius:8px;background:var(--dsw-alias-button-info-fill);color:var(--dsw-static-white);font:inherit;cursor:pointer}.dmp-search-button:disabled,.dmp-play-toggle:disabled,.dmp-button:disabled{opacity:.45;cursor:not-allowed}
.dmp-sidebar-results{flex:1 1 140px;min-height:92px;overflow-x:hidden;overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable;border-block:1px solid var(--dsw-alias-border-l1)}.dmp-empty{padding:18px 8px;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.55}.dmp-sidebar-message{flex:0 0 auto;margin:0;border-radius:7px;padding:7px 8px;font-size:12px}.dmp-error{border:1px solid var(--dsw-alias-error-border);color:var(--dsw-alias-error-label)}.dmp-notice{border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary)}
.dmp-track{appearance:none;display:grid;width:100%;grid-template-columns:36px minmax(0,1fr) 18px;align-items:center;gap:8px;border:0;border-bottom:1px solid var(--dsw-alias-border-l1);padding:7px 4px;background:transparent;color:inherit;text-align:left;cursor:pointer}.dmp-track:last-child{border-bottom:0}.dmp-track:hover,.dmp-track[data-on=true]{background:var(--dsw-alias-bg-hover)}.dmp-cover{display:grid;width:36px;height:36px;place-items:center;object-fit:cover;border-radius:6px;background:var(--dsw-alias-bg-l2);color:var(--dsw-alias-label-tertiary)}.dmp-track-copy,.dmp-title,.dmp-artist{display:block;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dmp-title{font-size:13px;font-weight:600}.dmp-artist,.dmp-license{color:var(--dsw-alias-label-tertiary);font-size:11px}.dmp-play-mark{font-size:12px;color:var(--dsw-alias-button-info-fill)}
.dmp-mini-player{display:grid;flex:0 0 auto;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:7px;border-radius:9px;padding:7px;background:var(--dsw-alias-bg-hover)}.dmp-play-toggle{width:34px;height:34px}.dmp-now{min-width:0}.dmp-now strong,.dmp-now small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dmp-now strong{font-size:12px}.dmp-now small,.dmp-time{color:var(--dsw-alias-label-tertiary);font-size:10px}.dmp-progress{grid-column:2/4;width:100%;height:3px;margin:0;accent-color:var(--dsw-alias-button-info-fill)}.dmp-mini-player[data-empty=true] .dmp-progress{opacity:.35}
.dmp-audio-host{position:fixed;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);opacity:0;pointer-events:none}.dmp-generator-overlay{position:absolute;inset:0 var(--dmp-conversation-width,460px) 0 var(--dmp-sidebar-width,240px);z-index:30;overflow:auto;border-right:1px solid var(--dsw-alias-border-l2);padding:28px clamp(20px,5vw,64px);background:var(--dsw-alias-bg-base);box-shadow:var(--dsw-shadow-l2);color:var(--dsw-alias-label-primary)}.dmp-generator-inner{max-width:760px}.dmp-generator-overlay h2{margin:18px 0 8px;font-size:24px}.dmp-generator-overlay p{color:var(--dsw-alias-label-secondary);line-height:1.6}.dmp-button{appearance:none;height:34px;border:0;border-radius:8px;padding:0 12px;background:var(--dsw-alias-button-info-fill);color:var(--dsw-static-white);font:inherit;cursor:pointer}.dmp-button-secondary{background:var(--dsw-alias-bg-hover);color:inherit}.dmp-form{display:grid;gap:14px;margin-top:24px}.dmp-form label{display:grid;gap:6px}.dmp-check{display:flex!important;grid-template-columns:none!important;align-items:flex-start;gap:8px!important}.dmp-check input{margin-top:4px}.dmp-review{margin-top:22px;border-top:1px solid var(--dsw-alias-border-l1);padding-top:18px}.dmp-check-row{display:grid;grid-template-columns:18px minmax(0,1fr);gap:8px;padding:5px 0;font-size:13px}.dmp-path{overflow-wrap:anywhere;color:var(--dsw-alias-label-tertiary);font:12px/18px ui-monospace,SFMono-Regular,Consolas,monospace}
.dmp-button:focus-visible,.dmp-input:focus-visible,.dmp-search-button:focus-visible,.dmp-play-toggle:focus-visible,.dmp-progress:focus-visible,.dmp-source-select select:focus-visible,.dmp-track:focus-visible{outline:2px solid var(--dsw-alias-button-info-fill);outline-offset:2px}
@media(max-width:999px){.dmp-generator-overlay{left:56px!important;right:0!important}}
`
